title: 道言学堂 | Daoyan Academy
description: A new approach to Bible study integrating Double Discourse Theory (DDT) with traditional exegesis.
url: https://talk1.top
baseurl: ""
permalink: /:year/:month/:day/:title/
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
collections:
  en_studies:
    output: true
    permalink: /en/studies/:year/:month/:day/:title/
  zh_studies:
    output: true
    permalink: /studies/:year/:month/:day/:title/
defaults:
  - scope:
      path: ""
      type: en_studies
    values:
      layout: default
  - scope:
      path: ""
      type: zh_studies
    values:
      layout: default
  - scope:
      path: ""
      type: pages
    values:
      layout: default
incremental: true